apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-distributed 
  namespace: argocd
spec:
  destination:
    namespace: mimir    
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 5.4.1 
      chart: mimir-distributed 
      helm:
        valueFiles:
          - $values/values/mimir-overrides-enterprise.yaml
    - repoURL: https://github.com/pbmoses/grafana-stack-argo.git 
      targetRevision: HEAD 
      ref: values
  project: default
